[package]
name = "rsocket_rust_test"
version = "0.0.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
publish = false

[dev-dependencies]
log = "0.4"
futures = "0.3.5"
env_logger = "0.7.1"
bytes = "0.5.4"
hex = "0.4.2"
rand = "0.7.3"
serde = "1.0.111"
serde_derive = "1.0.111"

[dev-dependencies.rsocket_rust]
path = "../rsocket"
features = ["frame"]

[dev-dependencies.rsocket_rust_transport_tcp]
version = "0.5.3"

[dev-dependencies.rsocket_rust_transport_unix]
version = "0.5.3"

[dev-dependencies.rsocket_rust_transport_websocket]
version = "0.5.3"

[dev-dependencies.rsocket_rust_messaging]
version = "0.5.3"

[dev-dependencies.tokio]
version = "0.2.21"
default-features = false
features = ["full"]
