[workspace]

members = [
# core
"rsocket",
# transports
"rsocket-transport-tcp",
"rsocket-transport-websocket",
"rsocket-transport-wasm",
# extra
"rsocket-messaging",
# internal
"examples",
"rsocket-test",
]
