[package]
name = "rsocket_rust_transport_websocket"
version = "0.5.2"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/rsocket/rsocket-rust"
homepage = "https://github.com/rsocket/rsocket-rust"
description = "Websocket RSocket transport implementation."

[dependencies]
log = "0.4.8"
futures = "0.3.5"
bytes = "0.5.4"
url = "2.1.1"
tokio-tungstenite = "0.10.1"

[dependencies.rsocket_rust]
path = "../rsocket"
features = ["frame"]

[dependencies.tokio]
version = "0.2.20"
default-features = false
features = [ "rt-core", "rt-threaded", "tcp", "sync", "stream" ]
