[package]
name = "rsocket_rust_transport_wasm"
version = "0.5.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.4"
wasm-bindgen = "0.2.58"
wasm-bindgen-futures = "0.4.8"
js-sys = "0.3.35"
rsocket_rust = { path = "../rsocket", features = ["frame"] }

[dependencies.web-sys]
version = "0.3.35"
features = [
  "FileReader",
  "ProgressEvent",
  "Blob",
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
]