[package]
name = "examples"
version = "0.0.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
publish = false

[dev-dependencies]
log = "0.4.8"
env_logger = "0.7.1"
futures = "0.3.5"
clap = "2.33.1"
tokio-postgres = "0.5.4"
redis = "0.16.0"

[dev-dependencies.rsocket_rust]
path = "../rsocket"

[dev-dependencies.rsocket_rust_transport_tcp]
path = "../rsocket-transport-tcp"

[dev-dependencies.rsocket_rust_transport_unix]
path = "../rsocket-transport-unix"

[dev-dependencies.rsocket_rust_transport_websocket]
version = "0.5.2"
path = "../rsocket-transport-websocket"

[dev-dependencies.tokio]
version = "0.2.21"
default-features = false
features = ["full"]

[[example]]
name = "echo"
path = "echo.rs"

[[example]]
name = "proxy"
path = "proxy.rs"

[[example]]
name = "cli"
path = "cli.rs"

[[example]]
name = "qps"
path = "qps.rs"

[[example]]
name = "postgres"
path = "postgres.rs"

[[example]]
name = "redis"
path = "redis.rs"

[[example]]
name = "echo-uds"
path = "echo-uds.rs"

[[example]]
name = "echo-uds-client"
path = "echo-uds-client.rs"