[package]
name = "examples"
version = "0.0.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
publish = false

[dev-dependencies]
log = "0.4.8"
env_logger = "0.7.1"
futures = "0.3.5"
clap = "2.33.1"

[dev-dependencies.rsocket_rust]
version = "0.5.2"

[dev-dependencies.rsocket_rust_transport_tcp]
version = "0.5.2"

[dev-dependencies.rsocket_rust_transport_websocket]
version = "0.5.2"

[dev-dependencies.tokio]
version = "0.2.21"
default-features = false
features = ["full"]

[[example]]
name = "echo"
path = "echo.rs"

[[example]]
name = "proxy"
path = "proxy.rs"

[[example]]
name = "cli"
path = "cli.rs"

[[example]]
name = "qps"
path = "qps.rs"
