[package]
name = "rsocket_rust_transport_tcp"
version = "0.5.1"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/rsocket/rsocket-rust"
homepage = "https://github.com/rsocket/rsocket-rust"
description = "TCP RSocket transport implementation."

[dependencies]
log = "0.4.8"
futures = "0.3.4"
bytes = "0.5.4"

[dependencies.rsocket_rust]
version = "0.5.1"
path = "../rsocket"
features = ["frame"]

[dependencies.tokio]
version = "0.2.13"
default-features = false
features = [ "rt-core", "rt-threaded", "tcp", "sync", "stream" ]

[dependencies.tokio-util]
version = "0.2.0"
default-features = false
features = ["codec"]

