[package]
name = "rsocket_rust_transport_tcp"
version = "0.6.0"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/rsocket/rsocket-rust"
homepage = "https://github.com/rsocket/rsocket-rust"
description = "TCP RSocket transport implementation."

[dependencies]
log = "0.4.11"
futures = "0.3.8"
bytes = "0.6.0"
async-trait = "0.1.42"

[dependencies.rsocket_rust]
version = "0.6.0"
features = ["frame"]

[dependencies.tokio]
version = "0.3.5"
default-features = false
features = [ "rt", "rt-multi-thread", "net", "sync", "stream", "io-util", "macros" ]

[dependencies.tokio-util]
version = "0.5.1"
default-features = false
features = ["codec"]
